# Generated by Django 6.1.1 on 2026-10-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_task_created_at_task_due_date_project_task_project'),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='project_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='productivity.project'),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='score',
            field=models.FloatField(blank=True, help_text='Risk score, 0 to 100', null=True),
        ),
    ]
