# Generated by Django 5.2.17 on 2026-09-15 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProductivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('completed', models.IntegerField()),
                ('pending', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkloadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=200)),
                ('due', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('On track', 'On track'), ('At risk', 'At risk'), ('Not started', 'Not started')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('due', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('On track', 'On track'), ('At risk', 'At risk'), ('Not started', 'Not started')], max_length=20)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tasks', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
