# Generated by Django 5.2.17 on 2026-09-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('change', models.CharField(max_length=20)),
                ('trend', models.CharField(choices=[('up', 'up'), ('down', 'down')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('revenue', models.FloatField()),
                ('expenses', models.FloatField()),
            ],
        ),
    ]
