# Generated by Django 6.1.1 on 2026-10-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('productivity', '0002_task_created_at_task_due_date_project_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='target',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=14)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='productivity.project')),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='KPIValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('actual', models.FloatField()),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.kpi')),
            ],
            options={
                'ordering': ['period'],
                'constraints': [models.UniqueConstraint(fields=('kpi', 'period'), name='unique_kpi_period')],
            },
        ),
    ]
