from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from finance.models import KPI, RevenueMonth
from risk.models import RiskAlert
from productivity.models import TeamProductivity


def add_header(p, title):
    p.setFillColorRGB(0.059, 0.078, 0.125)  # #0F1420
    p.rect(0, 780, 612, 60, fill=1, stroke=0)
    p.setFillColorRGB(0.788, 0.635, 0.153)  # #C9A227
    p.setFont("Helvetica-Bold", 11)
    p.drawString(40, 815, "INDUSTRY — AI Executive Decision Agent")
    p.setFillColorRGB(1, 1, 1)
    p.setFont("Helvetica-Bold", 18)
    p.drawString(40, 795, title)
    p.setFillColorRGB(0, 0, 0)


def add_footer(p):
    p.setFont("Helvetica", 9)
    p.setFillColorRGB(0.47, 0.47, 0.47)
    p.drawString(40, 30, "Generated by AI Executive Decision Agent")


def build_executive_pdf():
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    add_header(p, "Executive Summary Report")

    y = 750
    p.setFont("Helvetica-Bold", 13)
    p.drawString(40, y, "Key Performance Indicators")
    y -= 20
    p.setFont("Helvetica", 10)
    for k in KPI.objects.all():
        p.drawString(50, y, f"- {k.label}: {k.value} ({k.change})")
        y -= 16

    y -= 15
    p.setFont("Helvetica-Bold", 13)
    p.drawString(40, y, "Risk Alerts")
    y -= 20
    p.setFont("Helvetica", 10)
    for r in RiskAlert.objects.all():
        p.drawString(50, y, f"- {r.project} — {r.risk} [{r.severity.upper()}]")
        y -= 16

    add_footer(p)
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer


def build_kpi_pdf():
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    add_header(p, "KPI Report")

    y = 750
    p.setFont("Helvetica", 10)
    for k in KPI.objects.all():
        p.drawString(50, y, f"{k.label}")
        p.drawString(280, y, f"{k.value}")
        p.drawString(400, y, f"{k.change}")
        y -= 18

    add_footer(p)
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer


def build_financial_pdf():
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    add_header(p, "Financial Report")

    y = 750
    p.setFont("Helvetica-Bold", 11)
    p.drawString(50, y, "Month")
    p.drawString(200, y, "Revenue (L)")
    p.drawString(350, y, "Expenses (L)")
    y -= 20
    p.setFont("Helvetica", 10)
    for r in RevenueMonth.objects.all():
        p.drawString(50, y, f"{r.month}")
        p.drawString(200, y, f"{r.revenue}")
        p.drawString(350, y, f"{r.expenses}")
        y -= 16

    add_footer(p)
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer


def build_risk_pdf():
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    add_header(p, "Risk Report")

    y = 750
    p.setFont("Helvetica", 10)
    for r in RiskAlert.objects.all():
        p.drawString(50, y, f"{r.project}")
        y -= 15
        p.setFillColorRGB(0.47, 0.47, 0.47)
        p.drawString(50, y, f"{r.risk} — Severity: {r.severity.upper()}")
        p.setFillColorRGB(0, 0, 0)
        y -= 22

    y -= 10
    p.setFont("Helvetica-Bold", 12)
    p.drawString(40, y, "Team Productivity Snapshot")
    y -= 20
    p.setFont("Helvetica", 10)
    for pr in TeamProductivity.objects.all():
        p.drawString(50, y, f"{pr.team}: {pr.completed}% completed, {pr.pending}% pending")
        y -= 16

    add_footer(p)
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer